### PR TITLE
Implement methods for `today` and `todayat`.

### PR DESCRIPTION
**Pull request by omus**
Implements `today(::TimeZone)` which provides the current date in the specified `TimeZone`. Additionally, `today_at(::Time, ::TimeZone)` was introduced which works similarly to `::Date + ::Time == ::DateTime` but instead returns a `ZonedDateTime`.

### CODE REVIEW

**Comment by omus** [comment]
I need to think about this more yet. I think it may make sense to implement an `at` as proposed in: https://github.com/JuliaLang/julia/issues/24814

**Comment by omus** [comment]
After looking at this again I think `at` gets a little to close to the functionality of the constructors. I do think there should be an easy way create a new `TimeType` by setting the `Time` but I think that may be outside the scope of this PR.

**Comment by rofinn** [comment]
This looks fine for now. I'd suggest removing the '_' in `today_at` as none of the other methods appear to use that convention.

**Comment by omus** [comment]
Thanks @rofinn. I expect `todayat` won't exist for a long time. I think this reveals that the design needs some additional work which I wrote up in #121

**Pull request merged**
