### PR TITLE
Update to Julia 0.7 syntax

### PR DESCRIPTION
**Pull request by omus**
Drops support for Julia 0.4 and 0.5. Replaces #85

### CODE REVIEW

**Comment by omus** [comment]
[AppVeyor failures](https://ci.appveyor.com/project/omus/timezones-jl/build/1.0.347/job/67k9precw7kyjdt4) appear to be https://github.com/JuliaPackaging/WinRPM.jl/issues/57

**Comment by JeffreySarnoff** [comment]
why would that failure occur here and not before these edits?

**Comment by omus** [comment]
> why would that failure occur here and not before these edits?

The issue had to do with a package server being down. Looks like it's working again and re-running the failed jobs now works.

**Comment by JeffreySarnoff** [comment]
yar

**Pull request merged**
