### PR TITLE
Compatibility with Julia 0.7.0-alpha

### PR DESCRIPTION
**Pull request by omus**

### CODE REVIEW

**Comment by ararslan** [comment]
To fix the CI failure on 0.7 related to Mocking you might be able to just add a `Pkg.add("Mocking")` in there.

**Comment by omus** [comment]
The issue is actually shown earlier and is from trying to install WinRPM on non-windows systems. This will continue to be a problem while Pkg3 doesn't support OS dependent package requirements.

**Comment by omus** [comment]
I'm considering temporarily dropping LightXML (which uses WinRPM) as a Windows requirement since it's only needed to parse the Windows to tzdata translation file.

**Comment by ararslan** [comment]
Would [EzXML](https://github.com/bicycle1885/EzXML.jl) be a suitable replacement? That uses BinaryProvider rather than BinDeps with WinRPM.

**Comment by omus** [comment]
@ararslan it looks like EzXML is a easy solution here. Thanks for mentioning it.

**Comment by omus** [comment]
😢 Looks like our XML issues aren't over. Seems like EzXML isn't yet compatible with Julia 0.7-alpha: https://github.com/bicycle1885/EzXML.jl/issues/66

**Comment by omus** [comment]
Well EzXML works on 0.6 everywhere and at least can be installed on 0.7 which allows Mac and Linux to succeed. Since this is an overall improvement I'll go ahead with this.

**Comment by ararslan** [comment]
The EzXML issues on 0.7 will be solved shortly: https://github.com/bicycle1885/EzXML.jl/issues/67

**Comment by omus** [comment]
I'll bump up the minimum requirement in another PR. Thanks for taking care of that @ararslan! ❤️

**Pull request merged**
