### PR TITLE
Restore RecipesBase dep to fix 1.6

### PR DESCRIPTION
**Pull request by ericphanson**
xref https://github.com/JuliaTime/TimeZones.jl/pull/459#issuecomment-2123418212

### CODE REVIEW

**Review by odow — APPROVED** [review]
It can probably be removed from `extras` and `targets`?

**Comment by ericphanson** [comment]
I'm not 100% sure, but it seems to have been there pre-#459 so I think it would make sense to leave it to keep this as a minimal revert of the broken bit

**Comment by omus** [comment]
My bad. It's way to easy to miss this? Why can't I have the CI fail for TimeZones itself?

**Comment by omus** [comment]
I've made another PR to add a CI check to ensure this doesn't happen again: https://github.com/JuliaTime/TimeZones.jl/pull/462

**Review by omus — APPROVED** [review]

**Pull request merged**
