### PR TITLE
Add conversions for Julian dates

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by giordano** [comment]
Thanks!  Any plan to tag a new release?  I'd like to be able to use this feature in a stable version :-)

**Comment by omus** [comment]
I wasn't planning on it but since you want it I should be able to tag something soon-ish.

**Comment by omus** [comment]
@giordano I tagged v0.5.1 which includes this PR: https://github.com/JuliaLang/METADATA.jl/pull/11904

**Comment by giordano** [comment]
Great, thank you so much!

**Pull request merged**
