### PR TITLE
Julia 1.0 ready

### PR DESCRIPTION
**Pull request by omus**

### CODE REVIEW

**Comment by omus** [comment]
Coverage will be missing for Windows until https://github.com/JuliaCI/Appveyor.jl/pull/8 is merged and appveyor.yml is update.

**Comment by omus** [comment]
Coverage is now back for Windows

**Comment by omus** [comment]
@andreasnoack this should be finished shortly. I was waiting on EzXML to get tagged.

**Comment by andreasnoack** [comment]
Great. Thanks for the update.

**Comment by omus** [comment]
AppVeyor has passed but the integration still says pending. Going to merge.

**Pull request merged**
